# Generated by Django 4.1.7 on 2023-03-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('e_mail', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField(max_length=128)),
                ('description', models.TextField()),
                ('client_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='licznik_czasu.client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_name', models.TextField(max_length=128)),
                ('description', models.TextField()),
                ('creation_date', models.DateField()),
                ('project_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='licznik_czasu.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTimer',
            fields=[
                ('timer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_started', models.TimeField()),
                ('time_ended', models.TimeField()),
                ('task_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='licznik_czasu.task')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('e_mail', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('project_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='licznik_czasu.project')),
            ],
        ),
    ]
