# Generated by Django 4.1.7 on 2023-03-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik_czasu', '0002_remove_project_client_id_remove_task_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='e_mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
