# Generated by Django 4.1.7 on 2023-03-23 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licznik_czasu', '0003_alter_client_e_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_permissions',
        ),
    ]
