# Generated by Django 4.1.7 on 2023-03-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licznik_czasu', '0005_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
