# Generated by Django 4.1.7 on 2023-03-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licznik_czasu', '0009_alter_employee_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_id',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
