# Generated by Django 4.1.7 on 2023-03-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licznik_czasu', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField(max_length=128)),
                ('description', models.TextField()),
                ('creation_date', models.DateField()),
                ('project_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='licznik_czasu.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.TimeField()),
                ('time_ended', models.TimeField()),
                ('task_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='licznik_czasu.task')),
            ],
        ),
    ]
